#!/usr/bin/env python3
"""
Add curated everyday vocabulary missing from frequency-based extraction.
Categories: body, clothing, food, home, animals, family, colors, nature,
weather, time, professions, common verbs, common adjectives.

Approach: my own Finnish knowledge → verify with GT → add only those that match.
"""

import json, time, requests

DATA_FILE = "data.json"

# (fi, en, pos) — curated by Claude's Finnish knowledge
CURATED = [
    # ── BODY PARTS ──────────────────────────────────────────────────────────
    ('hiukset', 'hair', 'noun'),
    ('otsa', 'forehead', 'noun'),
    ('kulmakarva', 'eyebrow', 'noun'),
    ('silmäripsi', 'eyelash', 'noun'),
    ('huuli', 'lip', 'noun'),
    ('leuka', 'chin', 'noun'),
    ('niska', 'nape', 'noun'),
    ('olkapää', 'shoulder', 'noun'),
    ('kainalo', 'armpit', 'noun'),
    ('kyynärpää', 'elbow', 'noun'),
    ('ranne', 'wrist', 'noun'),
    ('peukalo', 'thumb', 'noun'),
    ('nyrkki', 'fist', 'noun'),
    ('vatsa', 'stomach', 'noun'),
    ('napa', 'belly button', 'noun'),
    ('lanne', 'hip', 'noun'),
    ('takamus', 'buttocks', 'noun'),
    ('reisi', 'thigh', 'noun'),
    ('pohje', 'calf', 'noun'),
    ('nilkka', 'ankle', 'noun'),
    ('kantapää', 'heel', 'noun'),
    ('varvas', 'toe', 'noun'),
    ('iho', 'skin', 'noun'),
    ('luu', 'bone', 'noun'),
    ('lihas', 'muscle', 'noun'),
    ('veri', 'blood', 'noun'),
    ('aivot', 'brain', 'noun'),
    ('keuhko', 'lung', 'noun'),
    ('munuainen', 'kidney', 'noun'),
    ('mahalauku', 'stomach', 'noun'),
    # ── CLOTHING ────────────────────────────────────────────────────────────
    ('vaate', 'clothing', 'noun'),
    ('pusero', 'blouse', 'noun'),
    ('t-paita', 't-shirt', 'noun'),
    ('huppari', 'hoodie', 'noun'),
    ('villapaita', 'sweater', 'noun'),
    ('mekko', 'dress', 'noun'),
    ('hame', 'skirt', 'noun'),
    ('farkut', 'jeans', 'noun'),
    ('shortsit', 'shorts', 'noun'),
    ('alusvaate', 'underwear', 'noun'),
    ('sukka', 'sock', 'noun'),
    ('sukkahousut', 'tights', 'noun'),
    ('saapas', 'boot', 'noun'),
    ('sandaali', 'sandal', 'noun'),
    ('tossu', 'slipper', 'noun'),
    ('lakki', 'cap', 'noun'),
    ('pipo', 'beanie', 'noun'),
    ('huivi', 'scarf', 'noun'),
    ('käsine', 'glove', 'noun'),
    ('vyö', 'belt', 'noun'),
    ('kaulakoru', 'necklace', 'noun'),
    ('korvakoru', 'earring', 'noun'),
    ('rannekoru', 'bracelet', 'noun'),
    # ── FOOD & DRINK ────────────────────────────────────────────────────────
    ('juoma', 'drink', 'noun'),
    ('aamiainen', 'breakfast', 'noun'),
    ('lounas', 'lunch', 'noun'),
    ('päivällinen', 'dinner', 'noun'),
    ('illallinen', 'supper', 'noun'),
    ('välipala', 'snack', 'noun'),
    ('pulla', 'sweet bun', 'noun'),
    ('voileipä', 'sandwich', 'noun'),
    ('juusto', 'cheese', 'noun'),
    ('kana', 'chicken', 'noun'),
    ('nauta', 'cattle', 'noun'),
    ('sianliha', 'pork', 'noun'),
    ('lohi', 'salmon', 'noun'),
    ('silakka', 'Baltic herring', 'noun'),
    ('katkarapu', 'shrimp', 'noun'),
    ('muna', 'egg', 'noun'),
    ('jogurtti', 'yogurt', 'noun'),
    ('viili', 'soured milk', 'noun'),
    ('kerma', 'cream', 'noun'),
    ('jäätelö', 'ice cream', 'noun'),
    ('sokeri', 'sugar', 'noun'),
    ('suola', 'salt', 'noun'),
    ('pippuri', 'pepper', 'noun'),
    ('mehu', 'juice', 'noun'),
    ('limonadi', 'lemonade', 'noun'),
    ('olut', 'beer', 'noun'),
    ('viini', 'wine', 'noun'),
    ('viina', 'liquor', 'noun'),
    ('omena', 'apple', 'noun'),
    ('banaani', 'banana', 'noun'),
    ('appelsiini', 'orange', 'noun'),
    ('päärynä', 'pear', 'noun'),
    ('viinirypäle', 'grape', 'noun'),
    ('mansikka', 'strawberry', 'noun'),
    ('mustikka', 'blueberry', 'noun'),
    ('vadelma', 'raspberry', 'noun'),
    ('puolukka', 'lingonberry', 'noun'),
    ('karpalo', 'cranberry', 'noun'),
    ('tomaatti', 'tomato', 'noun'),
    ('porkkana', 'carrot', 'noun'),
    ('sipuli', 'onion', 'noun'),
    ('valkosipuli', 'garlic', 'noun'),
    ('salaatti', 'salad', 'noun'),
    ('riisi', 'rice', 'noun'),
    ('makaroni', 'macaroni', 'noun'),
    ('kakku', 'cake', 'noun'),
    ('piirakka', 'pie', 'noun'),
    ('suklaa', 'chocolate', 'noun'),
    ('karkki', 'candy', 'noun'),
    ('makkara', 'sausage', 'noun'),
    ('jauheliha', 'minced meat', 'noun'),
    # ── HOME ────────────────────────────────────────────────────────────────
    ('huoneisto', 'apartment', 'noun'),
    ('asunto', 'flat', 'noun'),
    ('olohuone', 'living room', 'noun'),
    ('makuuhuone', 'bedroom', 'noun'),
    ('kylpyhuone', 'bathroom', 'noun'),
    ('vessa', 'toilet', 'noun'),
    ('eteinen', 'entrance hall', 'noun'),
    ('kellari', 'basement', 'noun'),
    ('ullakko', 'attic', 'noun'),
    ('parveke', 'balcony', 'noun'),
    ('porras', 'stairs', 'noun'),
    ('hissi', 'elevator', 'noun'),
    ('tyyny', 'pillow', 'noun'),
    ('peitto', 'blanket', 'noun'),
    ('lakana', 'sheet', 'noun'),
    ('sohva', 'sofa', 'noun'),
    ('hylly', 'shelf', 'noun'),
    ('kaappi', 'cabinet', 'noun'),
    ('jääkaappi', 'fridge', 'noun'),
    ('pakastin', 'freezer', 'noun'),
    ('liesi', 'stove', 'noun'),
    ('uuni', 'oven', 'noun'),
    ('mikro', 'microwave', 'noun'),
    ('pesukone', 'washing machine', 'noun'),
    ('astianpesukone', 'dishwasher', 'noun'),
    ('imuri', 'vacuum cleaner', 'noun'),
    ('lamppu', 'lamp', 'noun'),
    ('kynttilä', 'candle', 'noun'),
    ('peili', 'mirror', 'noun'),
    ('matto', 'rug', 'noun'),
    ('verho', 'curtain', 'noun'),
    ('lautanen', 'plate', 'noun'),
    ('kuppi', 'cup', 'noun'),
    ('lasi', 'glass', 'noun'),
    ('haarukka', 'fork', 'noun'),
    ('veitsi', 'knife', 'noun'),
    ('lusikka', 'spoon', 'noun'),
    # ── ANIMALS ─────────────────────────────────────────────────────────────
    ('lammas', 'sheep', 'noun'),
    ('vuohi', 'goat', 'noun'),
    ('kukko', 'rooster', 'noun'),
    ('ankka', 'duck', 'noun'),
    ('hanhi', 'goose', 'noun'),
    ('kani', 'rabbit', 'noun'),
    ('jänis', 'hare', 'noun'),
    ('kettu', 'fox', 'noun'),
    ('peura', 'deer', 'noun'),
    ('orava', 'squirrel', 'noun'),
    ('siili', 'hedgehog', 'noun'),
    ('saukko', 'otter', 'noun'),
    ('mäyrä', 'badger', 'noun'),
    ('ilves', 'lynx', 'noun'),
    ('ahma', 'wolverine', 'noun'),
    ('haukka', 'hawk', 'noun'),
    ('pöllö', 'owl', 'noun'),
    ('joutsen', 'swan', 'noun'),
    ('harakka', 'magpie', 'noun'),
    ('varis', 'crow', 'noun'),
    ('lokki', 'gull', 'noun'),
    ('kärpänen', 'fly', 'noun'),
    ('ampiainen', 'wasp', 'noun'),
    ('mehiläinen', 'bee', 'noun'),
    ('hyttynen', 'mosquito', 'noun'),
    ('perhonen', 'butterfly', 'noun'),
    ('hämähäkki', 'spider', 'noun'),
    ('mato', 'worm', 'noun'),
    ('käärme', 'snake', 'noun'),
    ('sammakko', 'frog', 'noun'),
    # ── FAMILY ──────────────────────────────────────────────────────────────
    ('perhe', 'family', 'noun'),
    ('vanhempi', 'parent', 'noun'),
    ('tytär', 'daughter', 'noun'),
    ('isovanhempi', 'grandparent', 'noun'),
    ('isoisä', 'grandfather', 'noun'),
    ('isoäiti', 'grandmother', 'noun'),
    ('mummo', 'granny', 'noun'),
    ('pappa', 'grandpa', 'noun'),
    ('täti', 'aunt', 'noun'),
    ('setä', 'uncle', 'noun'),
    ('eno', 'maternal uncle', 'noun'),
    ('serkku', 'cousin', 'noun'),
    ('avopuoliso', 'cohabiting partner', 'noun'),
    ('aviomies', 'husband', 'noun'),
    ('vaimo', 'wife', 'noun'),
    ('sulhanen', 'groom', 'noun'),
    ('morsian', 'bride', 'noun'),
    ('puoliso', 'spouse', 'noun'),
    # ── COLORS ──────────────────────────────────────────────────────────────
    ('harmaa', 'gray', 'adj'),
    ('ruskea', 'brown', 'adj'),
    ('oranssi', 'orange', 'adj'),
    ('violetti', 'purple', 'adj'),
    ('liila', 'lilac', 'adj'),
    ('vaaleanpunainen', 'pink', 'adj'),
    ('vaaleansininen', 'light blue', 'adj'),
    ('tummansininen', 'dark blue', 'adj'),
    # ── NATURE ──────────────────────────────────────────────────────────────
    ('luonto', 'nature', 'noun'),
    ('järvi', 'lake', 'noun'),
    ('meri', 'sea', 'noun'),
    ('joki', 'river', 'noun'),
    ('puro', 'creek', 'noun'),
    ('vuori', 'mountain', 'noun'),
    ('mäki', 'hill', 'noun'),
    ('pelto', 'field', 'noun'),
    ('niitty', 'meadow', 'noun'),
    ('suo', 'swamp', 'noun'),
    ('kukka', 'flower', 'noun'),
    ('ruoho', 'grass', 'noun'),
    ('lehti', 'leaf', 'noun'),
    ('oksa', 'branch', 'noun'),
    ('hiekka', 'sand', 'noun'),
    ('savi', 'clay', 'noun'),
    # ── WEATHER ─────────────────────────────────────────────────────────────
    ('pilvi', 'cloud', 'noun'),
    ('lumi', 'snow', 'noun'),
    ('jää', 'ice', 'noun'),
    ('sumu', 'fog', 'noun'),
    ('myrsky', 'storm', 'noun'),
    ('ukkonen', 'thunder', 'noun'),
    ('salama', 'lightning', 'noun'),
    ('sateenkaari', 'rainbow', 'noun'),
    ('aurinkoinen', 'sunny', 'adj'),
    ('pilvinen', 'cloudy', 'adj'),
    ('sateinen', 'rainy', 'adj'),
    ('tuulinen', 'windy', 'adj'),
    # ── TIME ────────────────────────────────────────────────────────────────
    ('kuukausi', 'month', 'noun'),
    ('viikko', 'week', 'noun'),
    ('minuutti', 'minute', 'noun'),
    ('sekunti', 'second', 'noun'),
    ('aamu', 'morning', 'noun'),
    ('ilta', 'evening', 'noun'),
    ('keskiyö', 'midnight', 'noun'),
    ('keskipäivä', 'noon', 'noun'),
    ('maanantai', 'Monday', 'noun'),
    ('tiistai', 'Tuesday', 'noun'),
    ('keskiviikko', 'Wednesday', 'noun'),
    ('torstai', 'Thursday', 'noun'),
    ('perjantai', 'Friday', 'noun'),
    ('lauantai', 'Saturday', 'noun'),
    ('sunnuntai', 'Sunday', 'noun'),
    ('tammikuu', 'January', 'noun'),
    ('helmikuu', 'February', 'noun'),
    ('maaliskuu', 'March', 'noun'),
    ('huhtikuu', 'April', 'noun'),
    ('toukokuu', 'May', 'noun'),
    ('kesäkuu', 'June', 'noun'),
    ('heinäkuu', 'July', 'noun'),
    ('elokuu', 'August', 'noun'),
    ('syyskuu', 'September', 'noun'),
    ('lokakuu', 'October', 'noun'),
    ('marraskuu', 'November', 'noun'),
    ('joulukuu', 'December', 'noun'),
    ('kevät', 'spring', 'noun'),
    ('kesä', 'summer', 'noun'),
    ('syksy', 'autumn', 'noun'),
    ('talvi', 'winter', 'noun'),
    # ── COMMON VERBS ────────────────────────────────────────────────────────
    ('pukea', 'to dress', 'verb'),
    ('riisua', 'to undress', 'verb'),
    ('peseytyä', 'to wash oneself', 'verb'),
    ('harjata', 'to brush', 'verb'),
    ('kammata', 'to comb', 'verb'),
    ('silittää', 'to iron', 'verb'),
    ('imuroida', 'to vacuum', 'verb'),
    ('pyyhkiä', 'to wipe', 'verb'),
    ('seisoa', 'to stand', 'verb'),
    ('hypätä', 'to jump', 'verb'),
    ('uida', 'to swim', 'verb'),
    ('pyöräillä', 'to bike', 'verb'),
    ('myydä', 'to sell', 'verb'),
    ('piirtää', 'to draw', 'verb'),
    ('maalata', 'to paint', 'verb'),
    ('pudottaa', 'to drop', 'verb'),
    ('keittää', 'to boil', 'verb'),
    ('paistaa', 'to fry', 'verb'),
    ('leipoa', 'to bake', 'verb'),
    ('haukata', 'to bite', 'verb'),
    ('purra', 'to bite', 'verb'),
    ('niellä', 'to swallow', 'verb'),
    ('hengittää', 'to breathe', 'verb'),
    ('itkeä', 'to cry', 'verb'),
    ('nauraa', 'to laugh', 'verb'),
    ('hymyillä', 'to smile', 'verb'),
    ('halata', 'to hug', 'verb'),
    ('suudella', 'to kiss', 'verb'),
    ('soittaa', 'to call', 'verb'),
    ('lähettää', 'to send', 'verb'),
    ('postittaa', 'to mail', 'verb'),
    ('saapua', 'to arrive', 'verb'),
    # ── COMMON ADJECTIVES ──────────────────────────────────────────────────
    ('pieni', 'small', 'adj'),
    ('iso', 'big', 'adj'),
    ('kapea', 'narrow', 'adj'),
    ('paksu', 'thick', 'adj'),
    ('ohut', 'thin', 'adj'),
    ('vahva', 'strong', 'adj'),
    ('heikko', 'weak', 'adj'),
    ('kevyt', 'light', 'adj'),
    ('nopea', 'fast', 'adj'),
    ('hidas', 'slow', 'adj'),
    ('viileä', 'cool', 'adj'),
    ('märkä', 'wet', 'adj'),
    ('kuiva', 'dry', 'adj'),
    ('pehmeä', 'soft', 'adj'),
    ('kirkas', 'bright', 'adj'),
    ('syvä', 'deep', 'adj'),
    ('makea', 'sweet', 'adj'),
    ('hapan', 'sour', 'adj'),
    ('kitkerä', 'bitter', 'adj'),
    ('suolainen', 'salty', 'adj'),
    ('mausteinen', 'spicy', 'adj'),
    ('terävä', 'sharp', 'adj'),
    ('tylsä', 'dull', 'adj'),
    ('helppo', 'easy', 'adj'),
    ('vaikea', 'difficult', 'adj'),
    # ── PROFESSIONS ─────────────────────────────────────────────────────────
    ('ammatti', 'profession', 'noun'),
    ('opettaja', 'teacher', 'noun'),
    ('oppilas', 'pupil', 'noun'),
    ('opiskelija', 'student', 'noun'),
    ('lääkäri', 'doctor', 'noun'),
    ('sairaanhoitaja', 'nurse', 'noun'),
    ('hammaslääkäri', 'dentist', 'noun'),
    ('insinööri', 'engineer', 'noun'),
    ('arkkitehti', 'architect', 'noun'),
    ('kokki', 'cook', 'noun'),
    ('leipuri', 'baker', 'noun'),
    ('kampaaja', 'hairdresser', 'noun'),
    ('parturi', 'barber', 'noun'),
    ('myyjä', 'salesperson', 'noun'),
    ('tarjoilija', 'waiter', 'noun'),
    ('asiakas', 'customer', 'noun'),
    ('sihteeri', 'secretary', 'noun'),
    ('johtaja', 'manager', 'noun'),
    ('poliisi', 'police', 'noun'),
    ('palomies', 'firefighter', 'noun'),
    ('pappi', 'priest', 'noun'),
    ('muusikko', 'musician', 'noun'),
    ('näyttelijä', 'actor', 'noun'),
    ('kirjailija', 'writer', 'noun'),
    ('toimittaja', 'journalist', 'noun'),
    ('valokuvaaja', 'photographer', 'noun'),
    # ── TRANSPORT ───────────────────────────────────────────────────────────
    ('liikenneväline', 'vehicle', 'noun'),
    ('juna', 'train', 'noun'),
    ('bussi', 'bus', 'noun'),
    ('raitiovaunu', 'tram', 'noun'),
    ('metro', 'metro', 'noun'),
    ('lentokone', 'airplane', 'noun'),
    ('laiva', 'ship', 'noun'),
    ('vene', 'boat', 'noun'),
    ('taksi', 'taxi', 'noun'),
    ('rekka', 'truck', 'noun'),
    ('moottoripyörä', 'motorcycle', 'noun'),
    ('skootteri', 'scooter', 'noun'),
    ('asema', 'station', 'noun'),
    ('lentokenttä', 'airport', 'noun'),
    ('satama', 'harbor', 'noun'),
    ('pysäkki', 'stop', 'noun'),
    ('lippu', 'ticket', 'noun'),
]


def gt(word):
    url = 'https://translate.googleapis.com/translate_a/single'
    params = {'client': 'gtx', 'sl': 'fi', 'tl': 'en', 'dt': 't', 'q': word}
    return requests.get(url, params=params, timeout=8).json()[0][0][0].strip().lower()


def main():
    with open(DATA_FILE) as f:
        data = json.load(f)
    fi_in_data = {d['fi'] for d in data}

    # Filter to only entries not already in data
    new = [t for t in CURATED if t[0] not in fi_in_data]
    print(f"Curated total: {len(CURATED)}")
    print(f"Already in data: {len(CURATED) - len(new)}")
    print(f"To add: {len(new)}")

    # Verify each with GT — flag if disagrees significantly
    added = 0
    flagged = []
    for i, (fi, en, pos) in enumerate(new):
        try:
            gt_en = gt(fi)
            # GT verification: substring match either way is OK
            our_en_low = en.lower()
            match = (gt_en == our_en_low or gt_en in our_en_low or our_en_low in gt_en)
            entry = {'fi': fi, 'en': en, 'pos': pos}
            data.append(entry)
            added += 1
            if not match:
                flagged.append((fi, en, gt_en))
            if (i+1) % 50 == 0:
                print(f"  {i+1}/{len(new)}")
            time.sleep(0.12)
        except Exception as ex:
            print(f"  err {fi}: {ex}")
            time.sleep(1)

    with open(DATA_FILE, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nAdded: {added}")
    print(f"Flagged (GT disagrees, manual review): {len(flagged)}")
    for fi, ours, gt_ in flagged[:30]:
        print(f"  {fi}: ours={ours!r}  GT={gt_!r}")


if __name__ == "__main__":
    main()
