#!/usr/bin/env python3
"""
34b_write_claude_sv_data.py

Write Claude-inline EN→SV translations to ../sanakirja/claude_en_sv.jsonl.
Covers top ~600 EN keys. Claude (me) generated these translations directly.
Run: python3 34b_write_claude_sv_data.py
"""

import json, os

OUT = "../sanakirja/claude_en_sv.jsonl"

# Claude-generated EN→SV translations (common words by rank)
TRANSLATIONS = {
    "No": "nej",
    "be": "vara",
    "to have": "ha",
    "and": "och",
    "it": "det",
    "he": "han",
    "that": "att",
    "which": "som",
    "like that": "sådär",
    "so": "så",
    "year": "år",
    "but": "men",
    "also": "också",
    "only": "bara",
    "to get": "få",
    "if": "om",
    "this": "detta",
    "can": "kan",
    "to become": "bli",
    "to come": "komma",
    "you": "du",
    "now": "nu",
    "butter": "smör",
    "oh": "å",
    "to make": "göra",
    "as soon as": "så snart",
    "when": "när",
    "to hold": "hålla",
    "to keep": "behålla",
    "by": "vid",
    "than": "än",
    "new": "ny",
    "they": "de",
    "already": "redan",
    "here": "här",
    "all": "alla",
    "everyone": "alla",
    "good": "bra",
    "to say": "säga",
    "yes": "ja",
    "markka": "mark",
    "then": "sedan",
    "why": "varför",
    "great": "stor",
    "large": "stor",
    "to tell": "berätta",
    "or": "eller",
    "what": "vad",
    "much": "mycket",
    "thank you": "tack",
    "thanks": "tack",
    "how": "hur",
    "yet": "ännu",
    "own": "egen",
    "country": "land",
    "ground": "mark",
    "where": "var",
    "two": "två",
    "thing": "sak",
    "a/an": "en",
    "one": "en",
    "we": "vi",
    "last": "sista",
    "tail": "svans",
    "percent": "procent",
    "percentage": "procent",
    "who": "vem",
    "man": "man",
    "anyway": "ändå",
    "however": "dock",
    "very": "mycket",
    "after": "efter",
    "because": "för att",
    "time": "tid",
    "about": "om",
    "perhaps": "kanske",
    "first": "första",
    "off": "av",
    "to remain": "stanna",
    "to stay": "stanna",
    "there": "där",
    "work": "arbete",
    "Mr.": "herr",
    "mister": "herr",
    "to take": "ta",
    "back": "tillbaka",
    "to give": "ge",
    "to yield": "ge",
    "clear": "klar",
    "mind": "sinne",
    "mood": "humör",
    "sober": "nykter",
    "just": "just",
    "root": "rot",
    "to want": "vilja",
    "to begin": "börja",
    "to start": "starta",
    "self": "sig",
    "never": "aldrig",
    "to visit": "besöka",
    "visit": "besök",
    "always": "alltid",
    "town": "stad",
    "three": "tre",
    "to go": "gå",
    "part": "del",
    "area": "område",
    "size": "storlek",
    "whole": "hel",
    "right": "rätt",
    "thus": "alltså",
    "although": "även om",
    "even if": "även om",
    "child": "barn",
    "day": "dag",
    "government": "regering",
    "to know": "veta",
    "really": "verkligen",
    "small": "liten",
    "as": "som",
    "such as": "till exempel",
    "next": "nästa",
    "commune": "kommun",
    "municipality": "kommun",
    "other": "annan",
    "second": "andra",
    "at least": "åtminstone",
    "out": "ut",
    "few": "några",
    "little": "liten",
    "to use": "använda",
    "father": "far",
    "probably": "troligen",
    "any": "någon",
    "anything": "något",
    "lady": "dam",
    "therefore": "därför",
    "woman": "kvinna",
    "week": "vecka",
    "for example": "till exempel",
    "quite": "ganska",
    "leave": "ledighet",
    "to leave": "lämna",
    "to need": "behöva",
    "mother": "mor",
    "Russia": "Ryssland",
    "marketplace": "torg",
    "chapter": "kapitel",
    "number": "nummer",
    "old": "gammal",
    "tea": "te",
    "to arise": "uppstå",
    "to rise": "stiga",
    "to see": "se",
    "today": "idag",
    "something": "något",
    "too": "också",
    "to note": "notera",
    "to state": "konstatera",
    "attempt": "försök",
    "company": "företag",
    "to show": "visa",
    "help": "hjälp",
    "to help": "hjälpa",
    "again": "igen",
    "to follow": "följa",
    "important": "viktig",
    "to talk": "prata",
    "beginning": "början",
    "start": "start",
    "place": "plats",
    "home": "hem",
    "situation": "situation",
    "president": "president",
    "information": "information",
    "end": "slut",
    "finish": "slut",
    "immediately": "omedelbart",
    "right away": "genast",
    "way": "sätt",
    "world": "värld",
    "amount": "mängd",
    "fire": "eld",
    "to cost": "kosta",
    "to pay": "betala",
    "to demand": "kräva",
    "to require": "kräva",
    "boy": "pojke",
    "son": "son",
    "in": "i",
    "into": "in i",
    "to bring": "ta med",
    "certainly": "säkert",
    "to believe": "tro",
    "faith": "tro",
    "sure": "säker",
    "ever": "någonsin",
    "four": "fyra",
    "dead": "död",
    "many": "många",
    "more": "mer",
    "police": "polis",
    "soon": "snart",
    "race": "lopp",
    "to kill": "döda",
    "car": "bil",
    "to expect": "förvänta",
    "to wait": "vänta",
    "wait": "väntan",
    "activity": "verksamhet",
    "activities": "verksamheter",
    "gold": "guld",
    "darling": "älskling",
    "different": "olika",
    "surely": "säkert",
    "once": "en gång",
    "long": "lång",
    "result": "resultat",
    "money": "pengar",
    "to decide": "bestämma",
    "up": "upp",
    "down": "ner",
    "may": "får",
    "decision": "beslut",
    "ready": "klar",
    "Finnish": "finsk",
    "girl": "flicka",
    "use": "användning",
    "cause": "orsak",
    "reason": "anledning",
    "to grow": "växa",
    "case": "fall",
    "life": "liv",
    "doctor": "läkare",
    "to arrange": "ordna",
    "slightly": "lite",
    "to lead": "leda",
    "competition": "tävling",
    "school": "skola",
    "sometimes": "ibland",
    "sometime": "någon gång",
    "water": "vatten",
    "food": "mat",
    "house": "hus",
    "door": "dörr",
    "book": "bok",
    "road": "väg",
    "street": "gata",
    "city": "stad",
    "night": "natt",
    "morning": "morgon",
    "evening": "kväll",
    "hand": "hand",
    "head": "huvud",
    "eye": "öga",
    "heart": "hjärta",
    "name": "namn",
    "word": "ord",
    "letter": "brev",
    "question": "fråga",
    "answer": "svar",
    "problem": "problem",
    "idea": "idé",
    "story": "berättelse",
    "history": "historia",
    "fact": "fakta",
    "truth": "sanning",
    "thought": "tanke",
    "language": "språk",
    "people": "folk",
    "society": "samhälle",
    "state": "stat",
    "law": "lag",
    "peace": "fred",
    "war": "krig",
    "power": "makt",
    "force": "kraft",
    "change": "förändring",
    "plan": "plan",
    "system": "system",
    "order": "ordning",
    "step": "steg",
    "line": "linje",
    "point": "punkt",
    "side": "sida",
    "form": "form",
    "kind": "slag",
    "type": "typ",
    "level": "nivå",
    "space": "utrymme",
    "air": "luft",
    "sun": "sol",
    "forest": "skog",
    "sea": "hav",
    "lake": "sjö",
    "river": "flod",
    "mountain": "berg",
    "city center": "centrum",
    "table": "bord",
    "chair": "stol",
    "window": "fönster",
    "floor": "golv",
    "wall": "vägg",
    "room": "rum",
    "kitchen": "kök",
    "bed": "säng",
    "dream": "dröm",
    "sleep": "sömn",
    "to sleep": "sova",
    "to eat": "äta",
    "to drink": "dricka",
    "to run": "springa",
    "to walk": "gå",
    "to read": "läsa",
    "to write": "skriva",
    "to speak": "tala",
    "to hear": "höra",
    "to think": "tänka",
    "to feel": "känna",
    "to love": "älska",
    "to live": "leva",
    "to die": "dö",
    "to open": "öppna",
    "to close": "stänga",
    "to buy": "köpa",
    "to sell": "sälja",
    "to find": "hitta",
    "to lose": "förlora",
    "to win": "vinna",
    "to play": "spela",
    "to work": "arbeta",
    "to build": "bygga",
    "to break": "bryta",
    "to put": "lägga",
    "to turn": "vända",
    "to return": "återvända",
    "to meet": "möta",
    "to call": "ringa",
    "to ask": "fråga",
    "to try": "försöka",
    "to stop": "stoppa",
    "to continue": "fortsätta",
    "to move": "röra sig",
    "to send": "skicka",
    "to receive": "ta emot",
    "to pay": "betala",
    "to learn": "lära sig",
    "to teach": "undervisa",
    "to remember": "komma ihåg",
    "to forget": "glömma",
    "to understand": "förstå",
    "to explain": "förklara",
    "to stand": "stå",
    "to sit": "sitta",
    "to fall": "falla",
    "to throw": "kasta",
    "to catch": "fånga",
    "to carry": "bära",
    "to pull": "dra",
    "to push": "trycka",
    "to cut": "skära",
    "alone": "ensam",
    "together": "tillsammans",
    "happy": "glad",
    "sad": "ledsen",
    "afraid": "rädd",
    "angry": "arg",
    "tired": "trött",
    "strong": "stark",
    "weak": "svag",
    "fast": "snabb",
    "slow": "långsam",
    "high": "hög",
    "low": "låg",
    "hot": "varm",
    "cold": "kall",
    "warm": "varm",
    "cool": "sval",
    "heavy": "tung",
    "light": "lätt",
    "young": "ung",
    "beautiful": "vacker",
    "ugly": "ful",
    "dark": "mörk",
    "bright": "ljus",
    "hard": "hård",
    "soft": "mjuk",
    "loud": "hög",
    "quiet": "tyst",
    "clean": "ren",
    "dirty": "smutsig",
    "open": "öppen",
    "closed": "stängd",
    "free": "fri",
    "busy": "upptagen",
    "possible": "möjlig",
    "necessary": "nödvändig",
    "important": "viktig",
    "interesting": "intressant",
    "difficult": "svår",
    "easy": "lätt",
    "true": "sann",
    "false": "falsk",
    "same": "samma",
    "similar": "liknande",
    "dog": "hund",
    "cat": "katt",
    "bird": "fågel",
    "fish": "fisk",
    "horse": "häst",
    "cow": "ko",
    "pig": "gris",
    "sheep": "får",
    "tree": "träd",
    "flower": "blomma",
    "grass": "gräs",
    "bread": "bröd",
    "milk": "mjölk",
    "coffee": "kaffe",
    "sugar": "socker",
    "salt": "salt",
    "meat": "kött",
    "egg": "ägg",
    "cheese": "ost",
    "potato": "potatis",
    "apple": "äpple",
    "beer": "öl",
    "wine": "vin",
    "friend": "vän",
    "family": "familj",
    "brother": "bror",
    "sister": "syster",
    "husband": "man",
    "wife": "fru",
    "child": "barn",
    "student": "elev",
    "teacher": "lärare",
    "soldier": "soldat",
    "politician": "politiker",
    "minister": "minister",
    "king": "kung",
    "church": "kyrka",
    "God": "Gud",
    "love": "kärlek",
    "hope": "hopp",
    "to hope": "hoppas",
    "fear": "rädsla",
    "joy": "glädje",
    "pain": "smärta",
    "health": "hälsa",
    "disease": "sjukdom",
    "death": "död",
    "freedom": "frihet",
    "justice": "rättvisa",
    "economy": "ekonomi",
    "price": "pris",
    "market": "marknad",
    "bank": "bank",
    "tax": "skatt",
    "salary": "lön",
    "job": "jobb",
    "business": "affär",
    "industry": "industri",
    "agriculture": "jordbruk",
    "nature": "natur",
    "environment": "miljö",
    "energy": "energi",
    "technology": "teknik",
    "science": "vetenskap",
    "art": "konst",
    "music": "musik",
    "sport": "sport",
    "game": "spel",
    "match": "match",
    "team": "lag",
    "goal": "mål",
    "ball": "boll",
    "telephone": "telefon",
    "computer": "dator",
    "internet": "internet",
    "television": "television",
    "radio": "radio",
    "newspaper": "tidning",
    "news": "nyheter",
    "report": "rapport",
    "meeting": "möte",
    "agreement": "avtal",
    "contract": "kontrakt",
    "deal": "affär",
    "conference": "konferens",
    "election": "val",
    "parliament": "riksdag",
    "party": "parti",
    "vote": "röst",
    "support": "stöd",
    "to support": "stödja",
    "criticism": "kritik",
    "to criticize": "kritisera",
    "success": "framgång",
    "failure": "misslyckande",
    "experience": "erfarenhet",
    "knowledge": "kunskap",
    "skill": "färdighet",
    "ability": "förmåga",
    "chance": "chans",
    "opportunity": "möjlighet",
    "risk": "risk",
    "danger": "fara",
    "safety": "säkerhet",
    "security": "säkerhet",
    "protection": "skydd",
    "to protect": "skydda",
    "to defend": "försvara",
    "to attack": "attackera",
    "border": "gräns",
    "territory": "territorium",
    "region": "region",
    "north": "norr",
    "south": "söder",
    "east": "öster",
    "west": "väster",
    "kilometer": "kilometer",
    "meter": "meter",
    "hour": "timme",
    "minute": "minut",
    "second": "sekund",
    "century": "sekel",
    "decade": "decennium",
    "century": "sekel",
    "spring": "vår",
    "summer": "sommar",
    "autumn": "höst",
    "winter": "vinter",
    "January": "januari",
    "February": "februari",
    "March": "mars",
    "April": "april",
    "May": "maj",
    "June": "juni",
    "July": "juli",
    "August": "augusti",
    "September": "september",
    "October": "oktober",
    "November": "november",
    "December": "december",
    "Monday": "måndag",
    "Tuesday": "tisdag",
    "Wednesday": "onsdag",
    "Thursday": "torsdag",
    "Friday": "fredag",
    "Saturday": "lördag",
    "Sunday": "söndag",
    "to dress": "klä sig",
    "clothes": "kläder",
    "shirt": "skjorta",
    "shoes": "skor",
    "hat": "hatt",
    "bag": "väska",
    "money": "pengar",
    "coin": "mynt",
    "paper": "papper",
    "key": "nyckel",
    "car": "bil",
    "train": "tåg",
    "bus": "buss",
    "airplane": "flygplan",
    "ship": "skepp",
    "bicycle": "cykel",
    "station": "station",
    "airport": "flygplats",
    "hospital": "sjukhus",
    "hotel": "hotell",
    "restaurant": "restaurang",
    "shop": "affär",
    "store": "butik",
    "museum": "museum",
    "library": "bibliotek",
    "park": "park",
    "bridge": "bro",
    "building": "byggnad",
    "office": "kontor",
    "factory": "fabrik",
    "farm": "gård",
    "village": "by",
    "neighborhood": "grannskap",
    "district": "distrikt",
    "province": "provins",
    "capital": "huvudstad",
    "Finland": "Finland",
    "Sweden": "Sverige",
    "Norway": "Norge",
    "Denmark": "Danmark",
    "Germany": "Tyskland",
    "France": "Frankrike",
    "United Kingdom": "Storbritannien",
    "Europe": "Europa",
    "Asia": "Asien",
    "Africa": "Afrika",
    "America": "Amerika",
    "Helsinki": "Helsingfors",
    "Stockholm": "Stockholm",
    "to run": "springa",
    "to swim": "simma",
    "to fly": "flyga",
    "to dance": "dansa",
    "to sing": "sjunga",
    "to paint": "måla",
    "to draw": "rita",
    "to cook": "laga mat",
    "to clean": "städa",
    "to wash": "tvätta",
    "to repair": "reparera",
    "to grow": "växa",
    "to plant": "plantera",
    "to travel": "resa",
    "to arrive": "anlända",
    "to depart": "avgå",
    "to choose": "välja",
    "to accept": "acceptera",
    "to refuse": "vägra",
    "to promise": "lova",
    "to warn": "varna",
    "to threaten": "hota",
    "to offer": "erbjuda",
    "to suggest": "föreslå",
    "to order": "beställa",
    "to command": "befalla",
    "to complain": "klaga",
    "to praise": "berömma",
    "to thank": "tacka",
    "to apologize": "be om ursäkt",
    "to forgive": "förlåta",
    "to share": "dela",
    "to compare": "jämföra",
    "to measure": "mäta",
    "to count": "räkna",
    "to add": "lägga till",
    "to reduce": "minska",
    "to increase": "öka",
    "to combine": "kombinera",
    "to divide": "dela",
    "to develop": "utveckla",
    "to improve": "förbättra",
    "to create": "skapa",
    "to destroy": "förstöra",
    "to save": "spara",
    "to spend": "spendera",
    "to invest": "investera",
    "to produce": "producera",
    "to export": "exportera",
    "to import": "importera",
    "to transport": "transportera",
    "to communicate": "kommunicera",
    "to organize": "organisera",
    "to manage": "hantera",
    "to control": "kontrollera",
    "to influence": "påverka",
    "to achieve": "uppnå",
    "to fail": "misslyckas",
    "to succeed": "lyckas",
    "to qualify": "kvalificera sig",
    "to represent": "representera",
    "to participate": "delta",
    "to cooperate": "samarbeta",
    "to compete": "tävla",
    "to prepare": "förbereda",
    "to plan": "planera",
    "to design": "designa",
    "to test": "testa",
    "to research": "forska",
    "to publish": "publicera",
    "to announce": "meddela",
    "to confirm": "bekräfta",
    "to deny": "förneka",
    "to agree": "hålla med",
    "to disagree": "inte hålla med",
    "to approve": "godkänna",
    "to reject": "avvisa",
    "to apply": "ansöka",
    "to hire": "anställa",
    "to fire": "avskeda",
    "to train": "träna",
    "to study": "studera",
    "to graduate": "ta examen",
    "to retire": "gå i pension",
    "to vote": "rösta",
    "to protest": "protestera",
    "to demonstrate": "demonstrera",
    "to negotiate": "förhandla",
    "to sign": "underteckna",
    "to celebrate": "fira",
    "to mourn": "sörja",
    "to pray": "be",
    "to marry": "gifta sig",
    "to divorce": "skilja sig",
}


def main():
    existing = set()
    if os.path.exists(OUT):
        with open(OUT) as f:
            for line in f:
                try:
                    rec = json.loads(line)
                    existing.add(rec.get("en", ""))
                except Exception:
                    pass

    added = 0
    with open(OUT, "a", encoding="utf-8") as f:
        for en, sv in TRANSLATIONS.items():
            if en not in existing:
                f.write(json.dumps({"en": en, "sv": sv}, ensure_ascii=False) + "\n")
                added += 1

    total = len(existing) + added
    print(f"Added {added} new entries. Total: {total} in {OUT}")


if __name__ == "__main__":
    main()
