#!/usr/bin/env python3
"""
34c_write_claude_sv_ext.py

Extension batch 2: Claude inline EN→SV translations for words not in 34b.
Covers ranks ~200-2000. Run after 34b.
"""

import json, os

OUT = "../sanakirja/claude_en_sv.jsonl"

TRANSLATIONS = {
    # Grammatical/functional words
    "correctly": "korrekt",
    "properly": "ordentligt",
    "to act": "agera",
    "to serve": "tjäna",
    "in shape": "i form",
    "minor": "liten",
    "okay": "okej",
    "Closed": "stängd",
    "attached": "bifogad",
    "expired": "utgången",
    "instance": "fall",
    "from here": "härifrån",
    "score": "poäng",
    "creator": "skapare",
    "habit": "vana",
    "chairman": "ordförande",
    "nearly": "nästan",
    "belief": "tro",
    "extinct": "utdöd",
    "Yeah": "ja",
    "former": "tidigare",
    "completed": "avslutad",
    "resolution": "beslut",
    "competitive": "konkurrenskraftig",
    "mrs": "fru",
    "still": "fortfarande",
    "later": "senare",
    "five": "fem",
    "possibility": "möjlighet",
    "initially": "inledningsvis",
    "period": "period",
    "season": "säsong",
    "term": "termin",
    "tomorrow": "imorgon",
    "even": "till och med",
    "ten": "tio",
    "better": "bättre",
    "over": "över",
    "past": "förbi",
    "pair": "par",
    "picture": "bild",
    "moment": "ögonblick",
    "best": "bäst",
    "current": "nuvarande",
    "quickly": "snabbt",
    "rapidly": "snabbt",
    "to estimate": "uppskatta",
    "guy": "kille",
    "enough": "tillräckligt",
    "set": "uppsättning",
    "tall": "lång",
    "loose": "lös",
    "such": "sådan",
    "leader": "ledare",
    "manager": "chef",
    "to look": "titta",
    "to mean": "betyda",
    "to answer": "svara",
    "to react": "reagera",
    "in addition": "dessutom",
    "in addition to": "utöver",
    "to be enough": "räcka",
    "to suffice": "räcka",
    "international": "internationell",
    "drive": "körning",
    "run": "löpning",
    "to chase": "jaga",
    "to drive": "köra",
    "whatever": "vad som helst",
    "matter": "ärende",
    "quietly": "tyst",
    "Swedish": "svensk",
    "big": "stor",
    "through": "genom",
    "completely": "helt",
    "totally": "totalt",
    "assistance": "hjälp",
    "spot": "plats",
    "group": "grupp",
    "god": "gud",
    "assignment": "uppdrag",
    "task": "uppgift",
    "away": "bort",
    "to happen": "hända",
    "objective": "mål",
    "target": "mål",
    "profit": "vinst",
    "victory": "seger",
    "journey": "resa",
    "travel": "resa",
    "trade": "handel",
    "captain": "kapten",
    "almost": "nästan",
    "else": "annat",
    "otherwise": "annars",
    "bell": "klocka",
    "clock": "klocka",
    "series": "serie",
    "hopefully": "förhoppningsvis",
    "comfortable": "bekväm",
    "cooperation": "samarbete",
    "member": "medlem",
    "emotion": "känsla",
    "feeling": "känsla",
    "sensation": "känsla",
    "to lower": "sänka",
    "research": "forskning",
    "directly": "direkt",
    "straight": "rakt",
    "crazy": "galen",
    "awkward": "besvärlig",
    "hello": "hej",
    "fine": "bra",
    "issue": "fråga",
    "to inform": "informera",
    "to notify": "meddela",
    "month": "månad",
    "fun": "kul",
    "pleasant": "trevlig",
    "third": "tredje",
    "to burn": "brinna",
    "program": "program",
    "schedule": "schema",
    "solution": "lösning",
    "healthy": "frisk",
    "in particular": "i synnerhet",
    "specifically": "specifikt",
    "natural": "naturlig",
    "simple": "enkel",
    "culture": "kultur",
    "direction": "riktning",
    "face": "ansikte",
    "position": "position",
    "movement": "rörelse",
    "moment": "ögonblick",
    "event": "händelse",
    "activity": "aktivitet",
    "organization": "organisation",
    "institution": "institution",
    "program": "program",
    "service": "tjänst",
    "product": "produkt",
    "method": "metod",
    "process": "process",
    "analysis": "analys",
    "development": "utveckling",
    "project": "projekt",
    "structure": "struktur",
    "function": "funktion",
    "condition": "tillstånd",
    "effect": "effekt",
    "influence": "inflytande",
    "role": "roll",
    "purpose": "syfte",
    "task": "uppgift",
    "goal": "mål",
    "value": "värde",
    "quality": "kvalitet",
    "standard": "standard",
    "type": "typ",
    "category": "kategori",
    "example": "exempel",
    "model": "modell",
    "version": "version",
    "stage": "steg",
    "phase": "fas",
    "step": "steg",
    "level": "nivå",
    "degree": "grad",
    "rate": "takt",
    "number": "antal",
    "total": "totalt",
    "average": "genomsnitt",
    "majority": "majoritet",
    "minority": "minoritet",
    "population": "befolkning",
    "generation": "generation",
    "community": "samhälle",
    "network": "nätverk",
    "relationship": "relation",
    "connection": "koppling",
    "impact": "inverkan",
    "effect": "effekt",
    "result": "resultat",
    "response": "svar",
    "reaction": "reaktion",
    "situation": "situation",
    "condition": "villkor",
    "crisis": "kris",
    "challenge": "utmaning",
    "problem": "problem",
    "solution": "lösning",
    "answer": "svar",
    "question": "fråga",
    "discussion": "diskussion",
    "debate": "debatt",
    "argument": "argument",
    "opinion": "åsikt",
    "view": "syn",
    "attitude": "attityd",
    "belief": "övertygelse",
    "value": "värde",
    "principle": "princip",
    "rule": "regel",
    "regulation": "reglering",
    "guideline": "riktlinje",
    "strategy": "strategi",
    "policy": "politik",
    "decision": "beslut",
    "choice": "val",
    "option": "alternativ",
    "alternative": "alternativ",
    "compromise": "kompromiss",
    "balance": "balans",
    "stability": "stabilitet",
    "growth": "tillväxt",
    "progress": "framsteg",
    "improvement": "förbättring",
    "reform": "reform",
    "revolution": "revolution",
    "conflict": "konflikt",
    "tension": "spänning",
    "violence": "våld",
    "crime": "brott",
    "punishment": "straff",
    "justice": "rättvisa",
    "responsibility": "ansvar",
    "duty": "plikt",
    "obligation": "skyldighet",
    "commitment": "åtagande",
    "promise": "löfte",
    "trust": "förtroende",
    "loyalty": "lojalitet",
    "solidarity": "solidaritet",
    "equality": "jämlikhet",
    "diversity": "mångfald",
    "inclusion": "inkludering",
    "participation": "deltagande",
    "democracy": "demokrati",
    "citizenship": "medborgarskap",
    "rights": "rättigheter",
    "freedom": "frihet",
    "independence": "självständighet",
    "sovereignty": "suveränitet",
    "relation": "relation",
    "cooperation": "samarbete",
    "partnership": "partnerskap",
    "alliance": "allians",
    "treaty": "fördrag",
    "negotiation": "förhandling",
    "settlement": "uppgörelse",
    "resolution": "resolution",
    "crisis management": "krishantering",
    "aid": "hjälp",
    "support": "stöd",
    "assistance": "bistånd",
    "investment": "investering",
    "trade": "handel",
    "export": "export",
    "import": "import",
    "production": "produktion",
    "consumption": "konsumtion",
    "demand": "efterfrågan",
    "supply": "utbud",
    "market": "marknad",
    "competition": "konkurrens",
    "industry": "industri",
    "sector": "sektor",
    "enterprise": "företag",
    "corporation": "bolag",
    "bank": "bank",
    "finance": "finans",
    "budget": "budget",
    "cost": "kostnad",
    "revenue": "intäkt",
    "income": "inkomst",
    "expenditure": "utgift",
    "benefit": "förmån",
    "risk": "risk",
    "loss": "förlust",
    "gain": "vinst",
    "debt": "skuld",
    "credit": "kredit",
    "loan": "lån",
    "interest": "ränta",
    "inflation": "inflation",
    "unemployment": "arbetslöshet",
    "poverty": "fattigdom",
    "welfare": "välfärd",
    "pension": "pension",
    "insurance": "försäkring",
    "healthcare": "sjukvård",
    "education": "utbildning",
    "research": "forskning",
    "innovation": "innovation",
    "technology": "teknik",
    "digital": "digital",
    "media": "media",
    "communication": "kommunikation",
    "information": "information",
    "data": "data",
    "analysis": "analys",
    "report": "rapport",
    "survey": "enkät",
    "study": "studie",
    "results": "resultat",
    "findings": "fynd",
    "conclusion": "slutsats",
    "recommendation": "rekommendation",
    "evaluation": "utvärdering",
    "assessment": "bedömning",
    "review": "genomgång",
    "audit": "granskning",
    "inspection": "inspektion",
    "monitoring": "övervakning",
    "control": "kontroll",
    "management": "förvaltning",
    "administration": "administration",
    "leadership": "ledarskap",
    "governance": "styrning",
    "authority": "myndighet",
    "power": "makt",
    "influence": "inflytande",
    "capacity": "kapacitet",
    "resource": "resurs",
    "funding": "finansiering",
    "grant": "bidrag",
    "subsidy": "subvention",
    "donation": "donation",
    "contribution": "bidrag",
    "initiative": "initiativ",
    "proposal": "förslag",
    "draft": "utkast",
    "amendment": "ändring",
    "measure": "åtgärd",
    "action": "åtgärd",
    "effort": "ansträngning",
    "attempt": "försök",
    "commitment": "engagemang",
    "participation": "deltagande",
    "involvement": "delaktighet",
    "engagement": "engagemang",
    "interest": "intresse",
    "concern": "oro",
    "priority": "prioritet",
    "focus": "fokus",
    "attention": "uppmärksamhet",
    "awareness": "medvetenhet",
    "understanding": "förståelse",
    "perspective": "perspektiv",
    "approach": "metod",
    "framework": "ramverk",
    "context": "sammanhang",
    "background": "bakgrund",
    "basis": "grund",
    "foundation": "grund",
    "concept": "begrepp",
    "theory": "teori",
    "hypothesis": "hypotes",
    "assumption": "antagande",
    "evidence": "bevis",
    "proof": "bevis",
    "fact": "faktum",
    "detail": "detalj",
    "aspect": "aspekt",
    "dimension": "dimension",
    "element": "element",
    "component": "komponent",
    "factor": "faktor",
    "issue": "fråga",
    "topic": "ämne",
    "subject": "ämne",
    "theme": "tema",
    "content": "innehåll",
    "format": "format",
    "structure": "struktur",
    "design": "design",
    "pattern": "mönster",
    "style": "stil",
    "appearance": "utseende",
    "image": "bild",
    "symbol": "symbol",
    "sign": "tecken",
    "signal": "signal",
    "message": "meddelande",
    "response": "svar",
    "feedback": "återkoppling",
    "comment": "kommentar",
    "statement": "uttalande",
    "declaration": "deklaration",
    "announcement": "tillkännagivande",
    "notice": "meddelande",
    "warning": "varning",
    "instruction": "instruktion",
    "advice": "råd",
    "guidance": "vägledning",
    "direction": "anvisning",
    "training": "utbildning",
    "exercise": "övning",
    "practice": "övning",
    "test": "test",
    "exam": "tentamen",
    "exam": "examen",
    "course": "kurs",
    "lesson": "lektion",
    "lecture": "föreläsning",
    "workshop": "workshop",
    "seminar": "seminarium",
    "conference": "konferens",
    "meeting": "möte",
    "session": "session",
    "event": "evenemang",
    "celebration": "firande",
    "festival": "festival",
    "competition": "tävling",
    "championship": "mästerskap",
    "tournament": "turnering",
    "match": "match",
    "game": "spel",
    "performance": "framträdande",
    "concert": "konsert",
    "exhibition": "utställning",
    "ceremony": "ceremoni",
    "ritual": "ritual",
    "tradition": "tradition",
    "custom": "sed",
    "practice": "praxis",
    "behavior": "beteende",
    "action": "handling",
    "reaction": "reaktion",
    "interaction": "interaktion",
    "communication": "kommunikation",
    "exchange": "utbyte",
    "discussion": "diskussion",
    "conversation": "samtal",
    "dialogue": "dialog",
    "interview": "intervju",
    "speech": "tal",
    "presentation": "presentation",
    "description": "beskrivning",
    "explanation": "förklaring",
    "interpretation": "tolkning",
    "translation": "översättning",
    "version": "version",
    "edition": "utgåva",
    "publication": "publikation",
    "document": "dokument",
    "file": "fil",
    "record": "post",
    "account": "konto",
    "profile": "profil",
    "identity": "identitet",
    "character": "karaktär",
    "personality": "personlighet",
    "individual": "individ",
    "person": "person",
    "citizen": "medborgare",
    "resident": "invånare",
    "immigrant": "invandrare",
    "refugee": "flykting",
    "victim": "offer",
    "survivor": "överlevare",
    "witness": "vittne",
    "suspect": "misstänkt",
    "criminal": "brottsling",
    "prisoner": "fånge",
    "guard": "vakt",
    "officer": "tjänsteman",
    "official": "tjänsteman",
    "politician": "politiker",
    "diplomat": "diplomat",
    "ambassador": "ambassadör",
    "expert": "expert",
    "specialist": "specialist",
    "consultant": "konsult",
    "advisor": "rådgivare",
    "analyst": "analytiker",
    "researcher": "forskare",
    "scientist": "forskare",
    "journalist": "journalist",
    "reporter": "reporter",
    "editor": "redaktör",
    "author": "författare",
    "artist": "konstnär",
    "musician": "musiker",
    "actor": "skådespelare",
    "director": "regissör",
    "producer": "producent",
    "designer": "designer",
    "architect": "arkitekt",
    "engineer": "ingenjör",
    "technician": "tekniker",
    "worker": "arbetare",
    "employee": "anställd",
    "employer": "arbetsgivare",
    "entrepreneur": "företagare",
    "investor": "investerare",
    "trader": "handlare",
    "farmer": "bonde",
    "fisherman": "fiskare",
    "hunter": "jägare",
    "pilot": "pilot",
    "driver": "förare",
    "chef": "kock",
    "nurse": "sjuksköterska",
    "lawyer": "advokat",
    "judge": "domare",
    "priest": "präst",
    "volunteer": "volontär",
    "activist": "aktivist",
    "leader": "ledare",
    "follower": "anhängare",
    "opponent": "motståndare",
    "ally": "allierad",
    "colleague": "kollega",
    "partner": "partner",
    "competitor": "konkurrent",
    "customer": "kund",
    "client": "klient",
    "user": "användare",
    "visitor": "besökare",
    "tourist": "turist",
    "passenger": "passagerare",
    "student": "student",
    "graduate": "examinerad",
    "professor": "professor",
    "politician": "politiker",
    "minister": "minister",
    "senator": "senator",
    "mayor": "borgmästare",
    "general": "general",
    "commander": "befälhavare",
    "soldier": "soldat",
    "officer": "officer",
    "sailor": "sjöman",
    "police officer": "polis",
    "firefighter": "brandman",
    "paramedic": "sjukvårdare",
    "surgeon": "kirurg",
    "physician": "läkare",
    "pharmacist": "apotekare",
    "dentist": "tandläkare",
    "veterinarian": "veterinär",
    "psychologist": "psykolog",
    "therapist": "terapeut",
    "social worker": "socialarbetare",
    "accountant": "revisor",
    "secretary": "sekreterare",
    "assistant": "assistent",
    "representative": "representant",
    "spokesperson": "talesperson",
    "interpreter": "tolk",
    "guide": "guide",
    "instructor": "instruktör",
    "coach": "tränare",
    "referee": "domare",
    "judge": "domare",
    "athlete": "idrottare",
    "champion": "mästare",
    "winner": "vinnare",
    "loser": "förlorare",
    "participant": "deltagare",
    "audience": "publik",
    "spectator": "åskådare",
    "fan": "supporter",
    "member": "medlem",
    "colleague": "kollega",
    "neighbor": "granne",
    "stranger": "okänd",
    "enemy": "fiende",
    "hero": "hjälte",
    "victim": "offer",
    "survivor": "överlevare",
    "baby": "bebis",
    "teenager": "tonåring",
    "adult": "vuxen",
    "elderly": "äldre",
    "ancestor": "förfader",
    "descendant": "ättling",
    "relative": "släkting",
    "grandfather": "farfar",
    "grandmother": "farmor",
    "uncle": "farbror",
    "aunt": "faster",
    "cousin": "kusin",
    "nephew": "nevö",
    "niece": "niece",
    "twin": "tvilling",
    "couple": "par",
    "widow": "änka",
    "orphan": "föräldralös",
    # Colors
    "red": "röd",
    "blue": "blå",
    "green": "grön",
    "yellow": "gul",
    "black": "svart",
    "white": "vit",
    "grey": "grå",
    "gray": "grå",
    "orange": "orange",
    "purple": "lila",
    "pink": "rosa",
    "brown": "brun",
    # Numbers
    "six": "sex",
    "seven": "sju",
    "eight": "åtta",
    "nine": "nio",
    "eleven": "elva",
    "twelve": "tolv",
    "thirteen": "tretton",
    "fourteen": "fjorton",
    "fifteen": "femton",
    "twenty": "tjugo",
    "hundred": "hundra",
    "thousand": "tusen",
    "million": "miljon",
    "billion": "miljard",
    "half": "hälften",
    "quarter": "kvartal",
    # Common verbs
    "to gain": "vinna",
    "to lose weight": "gå ner i vikt",
    "to increase": "öka",
    "to decrease": "minska",
    "to expand": "expandera",
    "to shrink": "krympa",
    "to merge": "slå ihop",
    "to split": "dela",
    "to connect": "koppla samman",
    "to disconnect": "koppla bort",
    "to activate": "aktivera",
    "to deactivate": "inaktivera",
    "to enable": "möjliggöra",
    "to disable": "inaktivera",
    "to block": "blockera",
    "to allow": "tillåta",
    "to deny": "neka",
    "to permit": "tillåta",
    "to forbid": "förbjuda",
    "to ban": "förbjuda",
    "to restrict": "begränsa",
    "to limit": "begränsa",
    "to extend": "förlänga",
    "to delay": "fördröja",
    "to accelerate": "påskynda",
    "to progress": "framskrida",
    "to regress": "gå bakåt",
    "to advance": "gå framåt",
    "to retreat": "dra sig tillbaka",
    "to escape": "fly",
    "to hide": "gömma sig",
    "to seek": "söka",
    "to search": "söka",
    "to discover": "upptäcka",
    "to reveal": "avslöja",
    "to show": "visa",
    "to hide": "dölja",
    "to prove": "bevisa",
    "to confirm": "bekräfta",
    "to deny": "förneka",
    "to admit": "erkänna",
    "to confess": "bekänna",
    "to accuse": "anklaga",
    "to defend": "försvara",
    "to protect": "skydda",
    "to attack": "attackera",
    "to fight": "kämpa",
    "to resist": "motstå",
    "to surrender": "ge upp",
    "to negotiate": "förhandla",
    "to agree": "komma överens",
    "to resolve": "lösa",
    "to solve": "lösa",
    "to handle": "hantera",
    "to deal with": "hantera",
    "to face": "möta",
    "to overcome": "övervinna",
    "to struggle": "kämpa",
    "to suffer": "lida",
    "to endure": "uthärda",
    "to survive": "överleva",
    "to recover": "återhämta sig",
    "to heal": "läka",
    "to treat": "behandla",
    "to cure": "bota",
    "to prevent": "förebygga",
    "to avoid": "undvika",
    "to reduce": "minska",
    "to eliminate": "eliminera",
    "to remove": "ta bort",
    "to replace": "ersätta",
    "to substitute": "ersätta",
    "to maintain": "upprätthålla",
    "to sustain": "bibehålla",
    "to continue": "fortsätta",
    "to persist": "fortsätta",
    "to remain": "förbli",
    "to stay": "stanna",
    "to leave": "lämna",
    "to depart": "avgå",
    "to arrive": "anlända",
    "to reach": "nå",
    "to achieve": "uppnå",
    "to accomplish": "genomföra",
    "to complete": "slutföra",
    "to finish": "avsluta",
    "to end": "avsluta",
    "to terminate": "avbryta",
    "to cancel": "avboka",
    "to postpone": "skjuta upp",
    "to suspend": "avbryta",
    "to resume": "återuppta",
    "to restart": "starta om",
    "to repeat": "upprepa",
    "to review": "granska",
    "to revise": "revidera",
    "to update": "uppdatera",
    "to upgrade": "uppgradera",
    "to improve": "förbättra",
    "to enhance": "förstärka",
    "to optimize": "optimera",
    "to maximize": "maximera",
    "to minimize": "minimera",
    "to prioritize": "prioritera",
    "to focus": "fokusera",
    "to concentrate": "koncentrera",
    "to consider": "överväga",
    "to evaluate": "utvärdera",
    "to assess": "bedöma",
    "to analyze": "analysera",
    "to investigate": "undersöka",
    "to examine": "granska",
    "to identify": "identifiera",
    "to define": "definiera",
    "to describe": "beskriva",
    "to classify": "klassificera",
    "to categorize": "kategorisera",
    "to organize": "organisera",
    "to structure": "strukturera",
    "to arrange": "arrangera",
    "to coordinate": "samordna",
    "to implement": "genomföra",
    "to execute": "genomföra",
    "to apply": "tillämpa",
    "to establish": "etablera",
    "to create": "skapa",
    "to develop": "utveckla",
    "to introduce": "presentera",
    "to launch": "lansera",
    "to promote": "marknadsföra",
    "to spread": "sprida",
    "to distribute": "distribuera",
    "to deliver": "leverera",
    "to provide": "tillhandahålla",
    "to offer": "erbjuda",
    "to supply": "leverera",
    "to produce": "producera",
    "to manufacture": "tillverka",
    "to construct": "konstruera",
    "to assemble": "montera",
    "to install": "installera",
    "to operate": "driva",
    "to run": "driva",
    "to manage": "hantera",
    "to lead": "leda",
    "to direct": "leda",
    "to guide": "vägleda",
    "to advise": "råda",
    "to consult": "konsultera",
    "to recommend": "rekommendera",
    "to approve": "godkänna",
    "to authorize": "auktorisera",
    "to delegate": "delegera",
    "to assign": "tilldela",
    "to allocate": "fördela",
    "to invest": "investera",
    "to fund": "finansiera",
    "to finance": "finansiera",
    "to budget": "budgetera",
    "to spend": "spendera",
    "to save": "spara",
    "to earn": "tjäna",
    "to profit": "tjäna",
    "to charge": "ta betalt",
    "to collect": "samla in",
    "to raise": "samla in",
    # Common adjectives
    "afraid": "rädd",
    "angry": "arg",
    "anxious": "orolig",
    "awful": "hemsk",
    "bad": "dålig",
    "basic": "grundläggande",
    "calm": "lugn",
    "careful": "försiktig",
    "cheap": "billig",
    "clever": "klyftig",
    "complex": "komplex",
    "confident": "säker",
    "confused": "förvirrad",
    "correct": "korrekt",
    "creative": "kreativ",
    "cruel": "grym",
    "dangerous": "farlig",
    "deep": "djup",
    "determined": "beslutsam",
    "direct": "direkt",
    "efficient": "effektiv",
    "entire": "hel",
    "equal": "lika",
    "excellent": "utmärkt",
    "expensive": "dyr",
    "fair": "rättvis",
    "familiar": "bekant",
    "famous": "känd",
    "fantastic": "fantastisk",
    "flexible": "flexibel",
    "formal": "formell",
    "frequent": "frekvent",
    "fresh": "färsk",
    "friendly": "vänlig",
    "funny": "rolig",
    "generous": "generös",
    "genuine": "äkta",
    "global": "global",
    "guilty": "skyldig",
    "helpful": "hjälpsam",
    "honest": "ärlig",
    "huge": "enorm",
    "human": "mänsklig",
    "hungry": "hungrig",
    "ideal": "idealisk",
    "illegal": "olaglig",
    "immediate": "omedelbar",
    "independent": "oberoende",
    "individual": "individuell",
    "informal": "informell",
    "innocent": "oskyldig",
    "intense": "intensiv",
    "involved": "inblandad",
    "kind": "snäll",
    "known": "känd",
    "large": "stor",
    "legal": "laglig",
    "likely": "trolig",
    "limited": "begränsad",
    "local": "lokal",
    "logical": "logisk",
    "main": "huvud-",
    "major": "större",
    "married": "gift",
    "massive": "massiv",
    "maximum": "maximal",
    "mental": "mental",
    "minimum": "minimal",
    "modern": "modern",
    "multiple": "multipel",
    "mutual": "ömsesidig",
    "narrow": "smal",
    "national": "nationell",
    "negative": "negativ",
    "neutral": "neutral",
    "nice": "trevlig",
    "normal": "normal",
    "obvious": "uppenbar",
    "official": "officiell",
    "original": "original",
    "particular": "speciell",
    "perfect": "perfekt",
    "physical": "fysisk",
    "political": "politisk",
    "poor": "fattig",
    "popular": "populär",
    "positive": "positiv",
    "powerful": "kraftfull",
    "practical": "praktisk",
    "precise": "exakt",
    "primary": "primär",
    "private": "privat",
    "professional": "professionell",
    "proper": "lämplig",
    "public": "offentlig",
    "pure": "ren",
    "rapid": "snabb",
    "rational": "rationell",
    "realistic": "realistisk",
    "reasonable": "rimlig",
    "recent": "nylig",
    "regular": "regelbunden",
    "relevant": "relevant",
    "reliable": "pålitlig",
    "responsible": "ansvarig",
    "rich": "rik",
    "round": "rund",
    "rural": "landsbygd",
    "serious": "allvarlig",
    "significant": "betydande",
    "silent": "tyst",
    "social": "social",
    "specific": "specifik",
    "standard": "standard",
    "steady": "stabil",
    "strict": "sträng",
    "suitable": "lämplig",
    "technical": "teknisk",
    "temporary": "tillfällig",
    "terrible": "hemsk",
    "traditional": "traditionell",
    "transparent": "transparent",
    "typical": "typisk",
    "unique": "unik",
    "unlikely": "osannolik",
    "urban": "stads-",
    "useful": "användbar",
    "valid": "giltig",
    "various": "olika",
    "vital": "livsviktig",
    "wide": "bred",
    "willing": "villig",
    "wise": "klok",
    "wonderful": "underbar",
    "wrong": "fel",
    # Additional words from missing list
    "moment": "ögonblick",
    "fit": "passform",
    "dying": "döende",
    "current": "nuvarande",
    "guy": "kille",
    "onward": "vidare",
    "set": "uppsättning",
    "loud": "hög",
    "Swedish": "svensk",
    "Miss": "fröken",
    "well-behaved": "väluppfostrad",
    "to be able to": "kunna",
    "deuce": "det fan",
    "spot": "fläck",
    "assignment": "tilldelning",
    "away": "borta",
    "objective": "mål",
    "upright": "upprätt",
    "victory": "seger",
    "damn": "förbannat",
    "captain": "kapten",
    "else": "annars",
    "bell": "klocka",
    "hell": "helvete",
    "series": "serie",
    "comfortable": "bekväm",
    "for real": "på riktigt",
    "little old": "liten gammal",
    "from there": "därifrån",
    "limb": "lem",
    "inquest": "utredning",
    "Joensuu": "Joensuu",
    "to sound": "låta",
    "good-looking": "snygg",
    "too much": "för mycket",
    "forced": "tvingad",
    "Ltd": "AB",
    "llc": "AB",
    "fun": "rolig",
    "pleasant": "trevlig",
    "to provide": "tillhandahålla",
    "to be worth": "vara värd",
    "to burn": "brinna",
    "solution": "lösning",
    "healthy": "frisk",
    "specifically": "specifikt",
    "dance": "dans",
    "stress": "stress",
    "to stress": "stressa",
    "in the future": "i framtiden",
    "boat": "båt",
    "cup": "kopp",
    "average": "genomsnitt",
    "on average": "i genomsnitt",
    "intelligent": "intelligent",
    "consumer": "konsument",
    "judgment": "dom",
    "printer": "skrivare",
    "definitive": "definitiv",
    "final": "slutlig",
    "to leak": "läcka",
    "green": "grön",
    "flight": "flyg",
    "flying": "flygande",
    "fifth": "femte",
    "to rest": "vila",
    "technique": "teknik",
    "sweet": "söt",
    "network": "nätverk",
    "pants": "byxor",
    "trousers": "byxor",
    "lastly": "slutligen",
    "teaching": "undervisning",
    "tuition": "undervisning",
    "gate": "grind",
    "port": "hamn",
    "writer": "författare",
    "appropriate": "lämplig",
    "suitable": "lämplig",
    "on the left": "till vänster",
    "popularity": "popularitet",
    "concerned": "orolig",
    "attire": "klädsel",
    "outfit": "outfit",
    "neither": "varken",
    "turn": "tur",
    "bold": "djärv",
    "brave": "modig",
    "to cover": "täcka",
    "bullet": "kula",
    "aunt": "faster",
    "sum": "summa",
    "director general": "generaldirektör",
    "piece": "bit",
    "snack": "mellanmål",
    "available": "tillgänglig",
    "device": "enhet",
    "equipment": "utrustning",
    "adult": "vuxen",
    "medal": "medalj",
    "personnel": "personal",
    "plot": "tomt",
    "grounds": "mark",
    "justification": "motivering",
    "nationwide": "rikstäckande",
    "to translate": "översätta",
    "naked": "naken",
    "equally": "lika",
    "interested": "intresserad",
    "angel": "ängel",
    "high school": "gymnasium",
    "thief": "tjuv",
    "to ruin": "förstöra",
    "to spoil": "förstöra",
    "to deceive": "lura",
    "firstly": "för det första",
    "stone": "sten",
    "goods": "varor",
    "to flower": "blomma",
    "suspected": "misstänkt",
    "to prosper": "frodas",
    "crime": "brott",
    "honestly": "ärligt",
    "virus": "virus",
    "finale": "final",
    "priest": "präst",
    "simple": "enkel",
    "gait": "gång",
    "to disrupt": "störa",
    "to disturb": "störa",
    "route": "rutt",
    "pastor": "pastor",
    "civil servant": "tjänsteman",
    "girlfriend": "flickvän",
    "effective": "effektiv",
    "fat": "fett",
    "tradition": "tradition",
    "monkey": "apa",
    "to appeal": "tilltala",
    "to sink": "sjunka",
    "island": "ö",
    "nervous": "nervös",
    "subtitle": "undertext",
    "subtitles": "undertexter",
    "demand": "krav",
    "owing to": "på grund av",
    "thanks to": "tack vare",
    "in time": "i tid",
    "wind": "vind",
    "to cheat": "fuska",
    "socialist": "socialist",
    "department": "avdelning",
    "threat": "hot",
    "neighbor": "granne",
    "to kiss": "kyssa",
    "pressure": "tryck",
    "wedding": "bröllop",
    "unit": "enhet",
    "accidentally": "av misstag",
    "countryside": "landsbygd",
    "rural": "landsbygd",
    "traitor": "förrädare",
    "personal": "personlig",
    "special": "speciell",
    "storm": "storm",
    "color": "färg",
    "warning": "varning",
    "knife": "kniv",
    "yard": "gård",
    "internal": "intern",
    "aside": "åt sidan",
    "challenge": "utmaning",
    "to differ": "skilja sig",
    "to vary": "variera",
    "style": "stil",
    "moon": "måne",
    "normally": "normalt",
    "sword": "svärd",
    "number one": "nummer ett",
    "puppy": "valp",
    "more and more": "mer och mer",
    "to elect": "välja",
    "five": "fem",
    "shit": "skit",
    "period": "period",
    "season": "säsong",
    "term": "termin",
    "tomorrow": "imorgon",
    "for one": "för det första",
    "whom": "vem",
    "even": "till och med",
    "to win/prevail against": "vinna mot",
    "better": "bättre",
    "to gamble": "spela om pengar",
    "to take away": "ta bort",
    "to fit": "passa",
    "to estimate": "uppskatta",
    "onward": "framåt",
    "in addition": "dessutom",
    "to react": "reagera",
    "international": "internationell",
    "to chase": "jaga",
    "completely": "helt",
    "totally": "totalt",
    "god": "gud",
    "to happen": "hända",
    "profit": "vinst",
    "trade": "handel",
    "almost": "nästan",
    "otherwise": "annars",
    "bell": "klocka",
    "clock": "klocka",
    "series": "serie",
    "hopefully": "förhoppningsvis",
    "comfortable": "bekväm",
    "member": "medlem",
    "emotion": "känsla",
    "sensation": "känsla",
    "to lower": "sänka",
    "directly": "direkt",
    "straight": "rakt",
    "crazy": "galen",
    "hello": "hej",
    "fine": "bra",
    "to inform": "informera",
    "month": "månad",
    "pleasant": "trevlig",
    "third": "tredje",
    "program": "program",
    "schedule": "schema",
    "healthy": "frisk",
    "to look": "titta",
    "leader": "ledare",
    "manager": "chef",
    "to mean": "betyda",
    "enough": "nog",
    "set": "sätta",
    "such": "sådan",
    "tall": "lång",
    "loose": "lös",
    "quickly": "snabbt",
    "rapidly": "snabbt",
    "guy": "kille",
    "best": "bäst",
    "picture": "bild",
    "group": "grupp",
    "big": "stor",
    "matter": "sak",
    "quietly": "tyst",
    "through": "igenom",
    "away": "bort",
    "victory": "seger",
    "journey": "resa",
    "captain": "kapten",
    "else": "annat",
    "cooperation": "samarbete",
    "to answer": "svara",
    "later": "senare",
    "ten": "tio",
    "over": "över",
    "past": "förbi",
    "pair": "par",
    "moment": "ögonblick",
    "still": "fortfarande",
    "result": "resultat",
    "possibility": "möjlighet",
    "initially": "inledningsvis",
    "research": "forskning",
    "issue": "fråga",
    "task": "uppgift",
    "objective": "mål",
    "target": "mål",
}


def main():
    existing = set()
    if os.path.exists(OUT):
        with open(OUT) as f:
            for line in f:
                try:
                    rec = json.loads(line)
                    existing.add(rec.get("en", ""))
                except Exception:
                    pass

    added = 0
    with open(OUT, "a", encoding="utf-8") as f:
        for en, sv in TRANSLATIONS.items():
            if en not in existing:
                f.write(json.dumps({"en": en, "sv": sv}, ensure_ascii=False) + "\n")
                added += 1
                existing.add(en)

    total = len(existing)
    print(f"Added {added} new entries. Total: {total} in {OUT}")


if __name__ == "__main__":
    main()
